#!/bin/sh

# Author: databeille <contact@databeille.com>
# Date: February 13, 2015

WIFIDOG_IF=$(grep 'GatewayInterface' /etc/wifidog.conf | grep -v ^# | awk '{print $2}')
WIFIDOG_MAC=$(ifconfig $WIFIDOG_IF | grep HWaddr | awk '{print $NF}' | sed 's/://g' | tr '[a-z]' '[A-Z]')
WIFIDOG_GWID=$(grep 'GatewayID' /etc/wifidog.conf | grep -v ^# | awk '{print $2}')
[ "$WIFIDOG_GWID" = "" ] && WIFIDOG_GWID=$WIFIDOG_MAC
DASHBOARD_URL=$(grep "option url" /etc/config/apdashboard | awk '{print $3}' | sed 's/"//g' | sed "s/'//g")
DASHBOARD_PROTO=$(echo $DASHBOARD_URL | awk -F/ '{print $1}' | sed "s/://g")                                               
DASHBOARD_PATH="$DASHBOARD_PROTO:\/\/"
DASHBOARD_HOST=$(echo $DASHBOARD_URL | awk -F/ '{print $3}' | awk -F: '{print $1}')
DASHBOARD_PATH="$DASHBOARD_PATH$DASHBOARD_HOST"
DASHBOARD_PORT=$(echo $DASHBOARD_URL | awk -F/ '{print $3}' | awk -F: '{print $2}')
[ "$DASHBOARD_PORT" != "" ] && DASHBOARD_PATH="$DASHBOARD_PATH:$DASHBOARD_PORT"
DASHBOARD_PATH=$(echo $DASHBOARD_URL | sed "s/$DASHBOARD_PATH//g")                                 
DASHBOARD_PATH="$DASHBOARD_PATH/status?gw_id=$WIFIDOG_GWID"
